/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./types/worker-configuration.d.ts` (hash: 61e68ce8dc0845244cd535c3a3bfa4ae)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../app/entry.worker");
	}
	interface Env {
		SESSION_KV: KVNamespace;
		CART_KV: KVNamespace;
		ENVIRONMENT: "development" | "test" | "production";
		SESSION_SECRET: string;
		NODE_ENV: string;
		LOG_LEVEL: string;
		ENABLE_DEBUG_LOGGING: string;
		UPLOADS_BUCKET: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
