/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./types/worker-configuration.d.ts` (hash: 3be451de86aea491964913610950be3d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../app/entry.worker");
	}
	interface Env {
		SESSION_KV: KVNamespace;
		SESSION_SECRET: string;
		NODE_ENV: string;
		LOG_LEVEL: string;
		ENABLE_DEBUG_LOGGING: string;
		UPLOADS: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
